### ISSUE TITLE
Downloading JSON file only

### ISSUE THREAD

**Issue by Cupbox** [dnsev-h/eze#13]
For the bigger archives (>500mb) and previously archived big comics, the ability to download JSON files seperately so we can add them to those archives would be appreciated.
Also, could you expound on un-resized and fallback images? I can see they're the same size as the original so what is the difference?

**Comment by Tsubasaza** [comment]
I would like an explanation about fallback images too. Sometimes when I download galleries with tons of images, I get the fallback error but when I download it in batches, I get none... it makes no sense.

**Comment by dnsev-h** [comment]
There's a flaw in how the downloader works: it fetches all of the image download links before it actually downloads the images, and these image links can apparently expire after a certain length of time. This leads to the script attempting to download those images, getting an error code because the URL has expired, and therefore downloading the fallback image.

This doesn't affect smaller galleries and smaller batch downloads because of the URLs don't expire quickly enough to cause problems.

**Comment by Tsubasaza** [comment]
There are cases where I can download really large galleries without getting fallback image and short galleries with fallback image, also what exactly is a fallback image? Is it just the original after a second attempt?

**Comment by dnsev-h** [comment]
If I remember correctly, fallback images are the images that are loaded using the "Click here if the image fails loading" link. I think when the "fallback" text is displayed, that means the image wasn't a downscaled version.

Sometimes the download fails because the H@H connection fails.

**Comment by dnsev-h** [comment]
A feature for downloading just the gallery metadata JSON file is available in another repository.
https://github.com/dnsev-h/x
