### ISSUE TITLE
PNG to JPG/JPEG

### ISSUE THREAD

**Issue by bluefiberbread** [dnsev-h/eze#20]
I'm genuinely curious why you would ever think that's a good idea

**Comment by dnsev-h** [comment]
What do you mean?

**Comment by bluefiberbread** [comment]
Downloading a gallery with .PNG files will download it as .PNG, but the file extension will say .JPG. Firefox 56 with Greasemonkey, I think it's the same for newer versions of Firefox with Grease/Violentmonkey

**Comment by bluefiberbread** [comment]
https://exhentai.org/g/1186991/3a04cf35e8/

This gallery's original files is in .png. Downloading the original files with Eze turns it into .jpg.

**Comment by dnsev-h** [comment]
So the reason this happens is because the filename is pulled from the gallery pages. In this case, it's 019.jpg, even when the source is a .png.
![image](https://user-images.githubusercontent.com/10576365/36633770-23bd54fe-1969-11e8-97a1-969a5cb78974.png)

Some galleries do display these names using .png when the source is is a .png, e.g.
![image](https://user-images.githubusercontent.com/10576365/36633788-46bee86e-1969-11e8-8d2e-9496ef10158f.png)

But it seems that resized .png galleries have those changed to .jpg, which corresponds to the resized image.
